name: Update Profile README

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          # Pin the version of uv to use
          # uv-version: "0.1.18"
          # The version of Python to use
          python-version: "3.11"

      - name: Install dependencies
        run: uv pip install .
        env:
          UV_SYSTEM_PYTHON: "1"

      - name: Run update script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          python scripts/update_readme.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(profile): auto-update readme with repo stats"
          file_pattern: "profile/README.md"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
